VS2019 build fixes
BlockSettle/common pull request #2094
Opened 2020-09-16 18:28 UTC by sergey-chernikov

2020-09-17 09:00 UTC, Ation commented on build_scripts/qt_settings.py
Please check server build

2020-09-17 09:00 UTC, Ation requested changes
Please update script revisions for changed settings scripts ( except Qt )

2020-09-17 09:14 UTC, Ation commented on build_scripts/gtest_settings.py
> +        #result = subprocess.call(command)
why do we need that change?
what it have to do with visual studio?

2020-09-17 09:32 UTC, sergey-chernikov commented on build_scripts/gtest_settings.py
> +        #result = subprocess.call(command)
It's something wrong with CMake on Windows - it can't properly parse double quotes (") if passing an arg as a list. Works fine with string for some reason. I'll make it platform-conditional in all other cases (like in websocket_settings atm).

2020-09-17 13:12 UTC, sergey-chernikov commented on build_scripts/qt_settings.py
Server build now works - see https://github.com/scomil/BS_Private/pull/1256

2020-09-23 07:58 UTC, Ation approved these changes

2020-09-23 08:19 UTC, merged